# Generated by Django 4.1 on 2022-11-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_phone_data_dni_remove_data_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='nombre',
            new_name='name',
        ),
    ]
